### ISSUE TITLE
ffmpegPreviewImage - Errors

### ISSUE THREAD

**Issue by zbigniewbednarek** [bropat/ioBroker.eusec#180]
**Describe the bug**  
Whenever motion is detected by Eufy Cameras/Doorbell adapter downloading images/video (this part works) and next it tries to preview downloaded file and after that I'm getting following errors:

eufy-security.0
2021-10-26 14:32:43.765	error	ffmpegPreviewImage(): ffmpeg output:
eufy-security.0
2021-10-26 14:32:43.764	error	ffmpegPreviewImage(): An error occurred: ffmpeg exited with code 1: Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/T8010Number/last_event/T8140Number.jpeg':Output file #0 does not contain any stream

and after that:
ffmpegPreviewImage(): ffmpeg stderr:ffmpeg version 4.4-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2021 the FFmpeg developers built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516 configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg libavutil 56. 70.100 / 56. 70.100 libavcodec 58.134.100 / 58.134.100 libavformat 58. 76.100 / 58. 76.100 libavdevice 58. 13.100 / 58. 13.100 libavfilter 7.110.100 / 7.110.100 libswscale 5. 9.100 / 5. 9.100 libswresample 3. 9.100 / 3. 9.100 libpostproc 55. 9.100 / 55. 9.100[hls @ 0x43cc620] Skip ('#EXT-X-VERSION:3')[hls @ 0x43cc620] Cannot get correct #EXTINF value of segment /opt/iobroker/iobroker-data/eufy-security.0/T8010Number/last_event/T8Number.ts, set to default value to 1ms.[hls @ 0x43cc620] Opening '/opt/iobroker/iobroker-data/eufy-security.0/T8010Number/last_event/T814Number.ts' for reading[aac @ 0x43d82b0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.[aac @ 0x43d82b0] channel element 2.1 is not allocated[aac @ 0x43d82b0] Sample rate index in program config element does not match the sample rate index configured by the container.[aac @ 0x43d82b0] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.[aac @ 0x43d82b0] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)[aac @ 0x43d82b0] channel element 3.4 is not allocated[aac @ 0x43d82b0] Sample rate index in program config element does not match the sample rate index configured by the container.[aac @ 0x43d82b0] Inconsistent channel configuration.[aac @ 0x43d82b0] get_buffer() failed[aac @ 0x43d82b0] channel element 2.15 is not allocated[aac @ 0x43d82b0] Reserved bit set.[aac @ 0x43d82b0] Number of scalefactor bands in group (44) exceeds limit (43).[aac @ 0x43d82b0] Dependent coupling is not supported together with LTP Last message repeated 11 times[aac @ 0x43d82b0] Multiple frames in a packet.[aac @ 0x43d82b0] Sample rate index in program config element does not match the sample rate index configured by the container.[aac @ 0x43d82b0] Inconsistent channel configuration.[aac @ 0x43d82b0] get_buffer() failed[aac @ 0x43d82b0] Number of bands (5) exceeds limit (2).[aac @ 0x43d82b0] channel element 2.6 is not allocated[aac @ 0x43d82b0] channel element 2.4 is not allocated[aac @ 0x43d82b0] channel element 2.9 is not allocated[aac @ 0x43d82b0] Reserved bit set.[aac @ 0x43d82b0] Gain control is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.[aac @ 0x43d82b0] channel element 0.2 is not allocated[aac @ 0x43d82b0] Number of bands (17) exceeds limit (13).[hls @ 0x43cc620] decoding for stream 1 failed[hls @ 0x43cc620] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified sizeConsider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options[hls @ 0x43cc620] Could not find codec parameters for stream 1 (Audio: aac (LTP) ([15][0][0][0] / 0x000F), stereo, fltp): unspecified sample rateConsider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) optionsInput #0, hls, from '/opt/iobroker/iobroker-data/eufy-security.0/T8010Number/last_event/T814Number.m3u8': Duration: 00:00:00.00, start: 1.400000, bitrate: 1232 kb/s Program 0 Metadata: variant_bitrate : 0 Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc Metadata: variant_bitrate : 0 Stream #0:1: Audio: aac (LTP) ([15][0][0][0] / 0x000F), stereo, fltp Metadata: variant_bitrate : 0Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/T8010Number/last_event/T814Number.jpeg':Output file #0 does not contain any stream

ffmpegPreviewImage - station: T8010P2321053A27 device: T8140P6121140EE0 - Error [{}]
**To Reproduce**  
1. Go to Logs
2. Wait for motion detection for Eufy Camers
3. See error messages

**Expected behavior**  
There should be no errors.

**Versions:**  
Versions:

    Adapter version: <0.7.1>

    JS-Controller version: <v5.1.25> : v5.1.25

    Node version: <v14.18.1> : v14.18.1

    Operating system: <Linux raspberrypi 5.10.63-v7l+>

ffmpeg version 4.1.6-1~deb10u1+rpt2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)

Hope that this is the last error I'm struggling with. 

Thank you,
Zbigniew

**Comment by zbigniewbednarek** [comment]
Hello,
Any clue what might be wrong ? I saw similar issues in some communities, unfortunately without any solution :(

Thank you,
Zbigniew

**Comment by bropat** [comment]
Hi @zbigniewbednarek,

it could be a BUG. Must check this functionality again.

**Comment by zbigniewbednarek** [comment]
Hello,
FYI:Same on 7.3 version.

**Comment by Schmakus** [comment]
Same on 0.7.4

**Comment by locito09** [comment]
I set the recording time of the camera to 28s and then the error was no longer in the LOG for one day, but the error was in the LOG again the next day, could it be that it has something to do with the recording time?

Adapter Version 0.7.4

**Comment by MrDrache333** [comment]
Ive set the Recording Time to 0 sek. The Bug stays.
Maybe we have to upgrade FFmpeg?

**Comment by zbigniewbednarek** [comment]
Hello,
@bropat Did you have time to look at this issue ? 

Thanks!

**Comment by locito09** [comment]
the message no longer comes if the messages in the Eufy app are switched off when there is movement. The image is then accessed via this link and no error messages appear in the Iobroker log

https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2021/12/29/station/

if the image can be retrieved in this way:

https: //security-app-eu.eufylife.com .........

the error messages come back in the Iobroker LOG

I solved it like this, unfortunately the link in the telegram is very large

**Comment by zbigniewbednarek** [comment]
@locito09 
What do you mean by "switching off messages in the Eufy app" ? Are you speaking about disabling motion Detection or what ? 
Let me know 

Thanks!

**Comment by locito09** [comment]
no only the notifications

**Comment by JanLoebel** [comment]
I've disabled the notification for motion detection, but I'm getting this error when somebody is ringing the doorbell. And I can't turn off the notification for that. So any ideas why this only happens with enabled notifications?

**Comment by bropat** [comment]
Because when the adapter receives a push notification containing information about the video of the event, it attempts to download it.
In the second step, a screenshot is generated from the downloaded video. In this case there is an error in the second step.
I can only find out why this error occurs by obtaining a complete debug log.

FYI: In the next version, there will also be an option to disable the download of the video + generation of the screenshot when receiving a push notification.

**Comment by zbigniewbednarek** [comment]
@bropat 
I can provide you with "debug" logs .. just let me know how to set the to debug.

**Comment by locito09** [comment]
here is a log

`<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/migue/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/migue/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/migue/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/migue/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE-CH link="#0563C1" vlink="#954F72" style='tab-interval:35.4pt;
word-wrap:break-word'>




eufy-security.0 | 2022-01-21 10:38:11.249 | debug | [PushClient.handleHeartbeatAck] Heartbeat   acknowledge   [{"tag":1,"object":{"lastStreamIdReceived":12}}]
-- | -- | -- | --
eufy-security.0 | 2022-01-21 10:38:11.231 | debug | [PushClient.buildHeartbeatPingRequest]   heartbeatPingRequest [{"last_stream_id_received":13}]
eufy-security.0 | 2022-01-21 10:38:11.231 | debug | [PushClient.sendHeartbeat] Sending   heartbeat... [13]
eufy-security.0 | 2022-01-21 10:36:53.927 | error | ffmpegPreviewImage - station:   T8010P2320491CC6 device: T8210P00204911BC - Error [{}]
eufy-security.0 | 2022-01-21 10:36:53.927 | error | ffmpegPreviewImage(): ffmpeg stderr:ffmpeg   version 4.4.1-static https://johnvansickle.com/ffmpeg/   Copyright (c) 2000-2021 the FFmpeg developers built with gcc 8 (Debian   8.3.0-6) configuration: --enable-gpl --enable-version3 --enable-static   --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio   --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp   --enable-libgme --enable-gray --enable-libaom --enable-libfribidi   --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame   --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg   --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt   --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab   --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264   --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid   --enable-libzvbi --enable-libzimg libavutil 56. 70.100 / 56. 70.100   libavcodec 58.134.100 / 58.134.100 libavformat 58. 76.100 / 58. 76.100   libavdevice 58. 13.100 / 58. 13.100 libavfilter 7.110.100 / 7.110.100   libswscale 5. 9.100 / 5. 9.100 libswresample 3. 9.100 / 3. 9.100 libpostproc   55. 9.100 / 55. 9.100[hls @ 0x7282c80] Skip ('#EXT-X-VERSION:3')[hls @   0x7282c80] Cannot get correct #EXTINF value of segment   /opt/iobroker/iobroker-data/eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC0.ts,   set to default value to 1ms.[hls @ 0x7282c80] Opening   '/opt/iobroker/iobroker-data/eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC0.ts'   for reading[aac @ 0x7290380] Sample rate index in program config element does   not match the sample rate index configured by the container.[aac @ 0x7290380]   Reserved bit set.[aac @ 0x7290380] Number of bands (5) exceeds limit (2).[aac   @ 0x7290380] Dependent coupling is not supported together with LTP Last   message repeated 1 times[aac @ 0x7290380] Multiple frames in a packet.[aac @   0x7290380] Reserved bit set.[aac @ 0x7290380] Number of bands (12) exceeds   limit (9).[aac @ 0x7290380] channel element 3.1 is not allocated[aac @   0x7290380] Sample rate index in program config element does not match the   sample rate index configured by the container.[aac @ 0x7290380] Inconsistent   channel configuration.[aac @ 0x7290380] get_buffer() failed[aac @ 0x7290380]   More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg   version to the newest one from Git. If the problem still occurs, it means   that your file has a feature which has not been implemented.[aac @ 0x7290380]   Sample rate index in program config element does not match the sample rate   index configured by the container.[aac @ 0x7290380] Inconsistent channel   configuration.[aac @ 0x7290380] get_buffer() failed[aac @ 0x7290380] Reserved   bit set.[aac @ 0x7290380] invalid band type[hls @ 0x7282c80] decoding for   stream 1 failed[hls @ 0x7282c80] Could not find codec parameters for stream 0   (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified sizeConsider   increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000)   options[hls @ 0x7282c80] Could not find codec parameters for stream 1 (Audio:   aac (LTP) ([15][0][0][0] / 0x000F), stereo, fltp): unspecified sample   rateConsider increasing the value for the 'analyzeduration' (0) and 'probesize'   (5000000) optionsInput #0, hls, from   '/opt/iobroker/iobroker-data/eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC.m3u8':   Duration: 00:00:00.00, start: 1.400000, bitrate: 1232 kb/s Program 0   Metadata: variant_bitrate : 0 Stream #0:0: Video: h264 ([27][0][0][0] /   0x001B), none, 90k tbr, 90k tbn, 180k tbc Metadata: variant_bitrate : 0   Stream #0:1: Audio: aac (LTP) ([15][0][0][0] / 0x000F), stereo, fltp   Metadata: variant_bitrate : 0Output #0, image2, to   '/opt/iobroker/iobroker-data/eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC.jpeg':Output   file #0 does not contain any stream
eufy-security.0 | 2022-01-21 10:36:53.926 | error | ffmpegPreviewImage(): ffmpeg output:
eufy-security.0 | 2022-01-21 10:36:53.926 | error | ffmpegPreviewImage(): An error occurred:   ffmpeg exited with code 1: Output #0, image2, to   '/opt/iobroker/iobroker-data/eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC.jpeg':Output   file #0 does not contain any stream
eufy-security.0 | 2022-01-21 10:36:53.904 | debug | [EufySecurity.onStateChange] state   eufy-security.0.T8010P2320491CC6.cameras.T8210P00204911BC.last_event_video_url   changed: /eufy-security.0/T8010P2320491CC6/last_event/T8210P00204911BC.m3u8   (ack = true) was already acknowledged, ignore it...
eufy-security.0 | 2022-01-21 10:36:53.874 | debug | [FfmpegCommand] ffmpegStreamToHls():   Processing finished!
eufy-security.0 | 2022-01-21 10:36:53.859 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA CONTROL - Received expected sequence (seqNo: 11   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:53.857 | debug | [P2PClientProtocol.handleDataControl]   Station T8010P2320491CC6 - CMD_DOWNLOAD_FINISH [{"channel":0}]
eufy-security.0 | 2022-01-21 10:36:53.856 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":11,"header":{"commandId":1304,"bytesToRead":0,"channel":0,"signCode":0,"type":0},"bytesRead":0,"bytesToRead":0,"firstPartMessage":true,"messageSize":16}]
eufy-security.0 | 2022-01-21 10:36:53.856 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA CONTROL - received from host 192.168.188.125:12147 -   Processing sequence 11...
eufy-security.0 | 2022-01-21 10:36:51.951 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2283   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:51.951 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2283,"header":{"commandId":1301,"bytesToRead":191,"channel":0,"signCode":0,"type":0},"bytesRead":191,"bytesToRead":191,"firstPartMessage":true,"messageSize":733}]
eufy-security.0 | 2022-01-21 10:36:51.950 | debug | [P2PClientProtocol.handleDataBinaryAndVideo]   Station T8010P2320491CC6 - CMD_VIDEO_FRAME   [{"dataSize":6942,"metadata":{"streamType":2,"videoSeqNo":147,"videoFPS":15,"videoWidth":2560,"videoHeight":1920,"videoTimestamp":1642761399212,"videoDataLength":6917,"aesKey":""},"videoDataSize":6917}]
eufy-security.0 | 2022-01-21 10:36:51.950 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - received from host 192.168.188.125:12147 -   Processing sequence 2283...
eufy-security.0 | 2022-01-21 10:36:51.951 | debug | [P2PClientProtocol.handleDataBinaryAndVideo]   Station T8010P2320491CC6 - CMD_AUDIO_FRAME   [{"dataSize":191,"metadata":{"audioType":0,"audioSeqNo":157,"audioTimestamp":1642761399245,"audioDataLength":175},"audioDataSize":175}]
eufy-security.0 | 2022-01-21 10:36:51.949 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2282   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:51.950 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2283,"header":{"commandId":1300,"bytesToRead":6942,"channel":0,"signCode":0,"type":0},"bytesRead":6942,"bytesToRead":6942,"firstPartMessage":false,"messageSize":733}]
eufy-security.0 | 2022-01-21 10:36:51.949 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2282,"header":{"commandId":1300,"bytesToRead":6942,"channel":0,"signCode":0,"type":0},"bytesRead":6416,"bytesToRead":6942,"firstPartMessage":false,"messageSize":1024}]
eufy-security.0 | 2022-01-21 10:36:51.949 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - received from host 192.168.188.125:12147 -   Processing sequence 2282...
eufy-security.0 | 2022-01-21 10:36:51.948 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2281   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:51.948 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2281,"header":{"commandId":1300,"bytesToRead":6942,"channel":0,"signCode":0,"type":0},"bytesRead":5392,"bytesToRead":6942,"firstPartMessage":false,"messageSize":1024}]
eufy-security.0 | 2022-01-21 10:36:51.948 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - received from host 192.168.188.125:12147 -   Processing sequence 2281...
eufy-security.0 | 2022-01-21 10:36:51.947 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2280   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:51.947 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2280,"header":{"commandId":1300,"bytesToRead":6942,"channel":0,"signCode":0,"type":0},"bytesRead":4368,"bytesToRead":6942,"firstPartMessage":false,"messageSize":1024}]
eufy-security.0 | 2022-01-21 10:36:51.946 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - received from host 192.168.188.125:12147 -   Processing sequence 2280...
eufy-security.0 | 2022-01-21 10:36:51.940 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2279   queuedData.size: 0)
eufy-security.0 | 2022-01-21 10:36:51.940 | debug | [P2PClientProtocol.parseDataMessage]   Station T8010P2320491CC6 - Received data   [{"seqNo":2279,"header":{"commandId":1300,"bytesToRead":6942,"channel":0,"signCode":0,"type":0},"bytesRead":3344,"bytesToRead":6942,"firstPartMessage":false,"messageSize":1024}]
eufy-security.0 | 2022-01-21 10:36:51.939 | debug | [P2PClientProtocol.handleMsg] Station   T8010P2320491CC6 - DATA BINARY - Received expected sequence (seqNo: 2278   queuedData.size: 0)



<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Von
meinem iPhone gesendet<o:p></o:p></span></p>


</body>

</html>
`

**Comment by zbigniewbednarek** [comment]
@bropat 
Thank you for adding option for Automatic video download. Let me check :)

**Comment by felix530-h** [comment]
I think I have the same error.

Versions:
Adapter version:  v0.9.4
Node.js: v16.16.0
NPM: v8.11.0

Downloading work, but on ffmpegPreviewImage I get an error:
16:40:17.021	debug	[P2PClientProtocol.handleDataControl] Station DEVICENAME - CMD_DOWNLOAD_FINISH [{"channel":0}]
16:40:17.021	debug	[P2PClientProtocol.handleMsg] Station DEVICENAME - DATA CONTROL - Received expected sequence (seqNo: 3 queuedData.size: 0)
16:40:17.034	debug	[FfmpegCommand] ffmpegStreamToHls(): Processing finished!
16:40:17.045	silly	States user redis pmessage eusec.0.DEVICENAME.*/eusec.0.DEVICENAME.cameras.DEVICENAME.last_event_video_url:{"val":"/eusec.0/DEVICENAME/last_event/DEVICENAME.m3u8","ack":true,"ts":1662388817044,"q":0,"from":"system.adapter.eusec.0","user":"system.user.admin","lc":1662388218723}

16:40:17.050	debug	[euSec.onStateChange] state eusec.0.DEVICENAME.cameras.DEVICENAME.last_event_video_url changed: /eusec.0/DEVICENAME/last_event/DEVICENAME.m3u8 (ack = true) was already acknowledged, ignore it...

16:40:17.063	error	ffmpegPreviewImage(): An error occurred: ffmpeg exited with code 1: Output #0, image2, to '/opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event/DEVICENAME.jpeg':Output file #0 does not contain any stream

16:40:17.063	error	ffmpegPreviewImage(): ffmpeg output:
16:40:17.063	error	ffmpegPreviewImage(): ffmpeg stderr:ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2021 the FFmpeg developers built with gcc 8 (Debian 8.3.0-6) configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg libavutil 56. 70.100 / 56. 70.100 libavcodec 58.134.100 / 58.134.100 libavformat 58. 76.100 / 58. 76.100 libavdevice 58. 13.100 / 58. 13.100 libavfilter 7.110.100 / 7.110.100 libswscale 5. 9.100 / 5. 9.100 libswresample 3. 9.100 / 3. 9.100 libpostproc 55. 9.100 / 55. 9.100[hls @ 0x6716880] Skip ('#EXT-X-VERSION:3')[hls @ 0x6716880] Cannot get correct #EXTINF value of segment /opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event/DEVICENAME0.ts, set to default value to 1ms.[hls @ 0x6716880] Opening '/opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event/DEVICENAME0.ts' for reading[aac @ 0x67249c0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.[aac @ 0x67249c0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.[aac @ 0x67249c0] channel element 3.11 is not allocated[aac @ 0x67249c0] channel element 3.15 is not allocated[hls @ 0x6716880] decoding for stream 1 failed[hls @ 0x6716880] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified sizeConsider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options[hls @ 0x6716880] Could not find codec parameters for stream 1 (Audio: aac (SSR) ([15][0][0][0] / 0x000F), 7.1, fltp): unspecified sample rateConsider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) optionsInput #0, hls, from '/opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event/DEVICENAME.m3u8': Duration: 00:00:00.00, start: 1.400000, bitrate: 1232 kb/s Program 0 Metadata: variant_bitrate : 0 Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc Metadata: variant_bitrate : 0 Stream #0:1: Audio: aac (SSR) ([15][0][0][0] / 0x000F), 7.1, fltp Metadata: variant_bitrate : 0Output #0, image2, to '/opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event/DEVICENAME.jpeg':Output file #0 does not contain any stream
16:40:17.063	error	ffmpegPreviewImage - station: DEVICENAME device: DEVICENAME - Error [{}]

In what format is the video saved and ist the path "/opt/iobroker/iobroker-data/eusec.0/DEVICENAME/last_event" correct?
I think the m3u8 file is too small for a video.
55836   DEVICENAME0.ts
154   DEVICENAME.m3u8
39320   DEVICENAME0.jpeg

Thank you in advance!
