### ISSUE TITLE
[Bug]: last_event_pic_url  wrong (old) image

### ISSUE THREAD

**Issue by zoulhh** [bropat/ioBroker.eusec#302]
### Adapter version

0.9.8

### JS-Controller version

4.0.23

### Node version

18.11

### Operating System type

Unix

### Operating system version

Debian

### Describe the bug

The last_event_pic_url in a Eufy Wireless Doorbellcamera is not current but one day old. There have been many events ever since.

NOTE! After restarting the adapter it retrieves the current correct image.

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
