### ISSUE TITLE
[Bug]: state "battery" does not update since 2023-01-01

### ISSUE THREAD

**Issue by ioBandit** [bropat/ioBroker.eusec#316]
### Adapter version

0.9.9

### JS-Controller version

4.0.23

### Node version

16.17.1

### Operating System type

Linux

### Operating system version

Raspbian 10

### Describe the bug

the battery states from Eufy2 Pro cameras do not update since 2023-01-01. Timestamp and value remain from 2022-12-31. Worked correct before. Other states update correct. Battery values update correctly in Eufy APP.

### To reproduce

Check timestamp and value of state "battery" of Eufy2 Pro Cameras

**Comment by n0valis** [comment]
I have two eufycam 2 cameras and kind of the same problem.
I cannot confirm the date, because mine updated until a week ago. But then I had to charge the batteries and after that the values are not correct anymore. Showing 97% and  98% instead of 100%.
And that only happend after I restarted the adapter instance a couple of times. Before the values were stuck at a much lower level. So far nothing seems to happen. Both my cameras are still at 100% since I fully charged them three days ago. But the Adapter still shows  97% and  98%.
