### ISSUE TITLE
[Bug]: saveImage(): Error: TypeError [ERR_INVALID_URL]: Invalid URL:

### ISSUE THREAD

**Issue by loki-sft** [bropat/ioBroker.eusec#317]
### Adapter version

0.9.9.9

### JS-Controller version

4.0.24

### Node version

14.21.1

### Operating System type

Linux

### Operating system version

Debian 10.10

### Describe the bug

After starting the adapter I get errors:

<html>
<body>

eusec.0 | 2023-01-19 14:02:48.364 | error | saveImage(): Error: TypeError [ERR_INVALID_URL]: Invalid URL: T8410Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230113195619n.jpg - url: T8410Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230113195619n.jpg
-- | -- | -- | --
eusec.0 | 2023-01-19 14:02:48.134 | error | saveImage(): Error: TypeError [ERR_INVALID_URL]: Invalid URL: T8441Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230118175837n.jpg - url: T8441Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230118175837n.jpg
eusec.0 | 2023-01-19 14:02:48.124 | error | saveImage(): Error: TypeError [ERR_INVALID_URL]: Invalid URL: T8400Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230115190551n.jpg - url: T8400Pxxxxxxxx~/media/mmcblk0p1/Camera00/20230115190551n.jpg

</body>
</html>

### To reproduce

restart the adapter and enter captha

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
