### ISSUE TITLE
[Question]: Node 20 requirement is a bit steep & currently not the recommended version for iobroker

### ISSUE THREAD

**Issue by seb2010** [bropat/ioBroker.eusec#437]
### Ask your question

Hello. Is there a reason why the latest adapter version needs node 20 to work? I think rarely anyone is on that node version level. It is also not the current recommended node version for iobroker.
Any chance to make it downward compatible?
KR
SEB

**Comment by PhilippEngler** [comment]
> Is there a reason why the latest adapter version needs node 20 to work?

Yes, because of the dependencies. At least one (got) will require NodeJS v20.

> It is also not the current recommended node version for iobroker.

iobrocker is recommending NodeJS v20, also for existing installations. See [https://www.iobroker.net/#en/blog/2024_06_30](https://www.iobroker.net/#en/blog/2024_06_30)

Best, Philipp
(I'm not the developer of 'ioBrocker.eusec', but use the client for developing an integration into another system)

**Comment by mcm1957** [comment]
@seb2010 

> Hello. Is there a reason why the latest adapter version needs node 20 to work? I think rarely anyone is on that node version level. It is also not the current recommended node version for iobroker. Any chance to make it downward compatible? KR SEB

I must correct you.
**Since MAY 2024 node.js 20 is the RECOMMENDED node version for ioBroker.** Please see https://forum.iobroker.net/topic/74831/wir-empfehlen-node-js-20-x

So ist fully OK to require node 20 minimum. You should consider uodateing to node.js 20 if your operating system supports - or update your O/S otherwise. Please open a topic in forum (https://forum .iobroker.net) if required.

**Comment by seb2010** [comment]
Nevermind. I just wanted to highlight, that the requirement of node 20 might prohibit a lot of users (55% according to https://www.iobroker.net/#de/statistics) from using the adapter without doing a major update task to upgrade to node 20. Not something you would expect from an occasional adapter update run...

**Comment by mcm1957** [comment]
Updating node js is a one liner far away from a major update task:

``iob nodejs-update 20``

assuming you hav a still supported operating system installed.

**Comment by bropat** [comment]
@seb2010 

@PhilippEngler  and @mcm1957 have already said it all and I see it the same way.
